### ISSUE TITLE
Missing kerning pairs

### ISSUE THREAD

**Issue by oomek** [astiopin/sdf_atlas#1]
Some kerning pairs are not present in font.js file. For example Va Ve Wa We AV etc.
Additionally some fonts are not producing any output like BarlowCondensed-SemiBold.ttf
Update: Barlow condensed 1.408 didn't work, but a newer 1.422 downloaded from github worked, odd.

**Comment by oomek** [comment]
It seems like the modern kerning tables are unrecognised. I can only generete (still incomplete) kerning tables when I export the font in FontLab with legacy kerning tables ticked in the ttf profile.

**Comment by oomek** [comment]
Is this repo still maintained? I would really like to implement your method as it gives amazing results, but those missing kern pairs are a deal breaker. It seems like the atlas generator is not processing kerning classes.

**Comment by astiopin** [comment]
Font managing is pretty basic at the moment. Hinting on modern fonts with 2d glyph placement is not supported. You can use a full featured font library like freetype ([freetype](https://www.freetype.org/)) for font loading.

**Comment by oomek** [comment]
I actually want to get rid of freetype so I can scale text smoothly. I was experimenting with harfbuzz recently and It nicely returns proper kerning for ttf and otf for each glyph pairs, but it's a pain in the back to do it in js. I need to rewrite the displaying function in c++ to see how it looks.

**Comment by astiopin** [comment]
You can write TTF reading routine yourself. It's complicated but not THAT hard. I've used [apple](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html) and [microsoft](https://docs.microsoft.com/en-us/typography/opentype/spec/) spec pages for writing my TTF parsing [library](https://github.com/astiopin/sdf_atlas/blob/master/src/font.cpp). Look for the 'kerx' [table](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6kerx.html). Modern fonts store kerning there.

**Comment by oomek** [comment]
Actually most of the fonts I use store kerning in `gpos` table, hence the need for harfbuzz. I think that there is no need to reinvent the wheel in this particular situation. Maybe harfbuzz could also be used to extract the glyph data.

**Comment by astiopin** [comment]
Yes, using harfbuzz would probably be the best way.
