### ISSUE TITLE
Pixel Artefacts

### ISSUE THREAD

**Issue by DanielHerchenbach** [astiopin/sdf_atlas#10]
A few glyphs are exported with artefacts. This problem is really strange because the artefacts have a width of one pixel only. For the below example I also checked the path stored in the font and it is correct. The error occurs on a long line segment, nothing fancy so I have no idea what is going wrong.
I used the following font
[noto-sans-regular.zip](https://github.com/astiopin/sdf_atlas/files/5975642/noto-sans-regular.zip)
with -rh 43 -bs 5
on an Intel HD Graphics 5500.

![image](https://user-images.githubusercontent.com/33656504/107849918-a0184d00-6dfe-11eb-8db2-9cb2eca4c1ca.png)

![noto-sans-regular](https://user-images.githubusercontent.com/33656504/107849943-c5a55680-6dfe-11eb-910d-796becfeadf5.png)

**Comment by astiopin** [comment]
It's line segment approximation again. Looks like some discontinuity causes NaNs in the shader. I've changed approximation routine and lines are now parabola segments in range 100-100.001. Artifacts are gone on Intel but it may require more tweaking. Should investigate it more thoroughly.

**Comment by DanielHerchenbach** [comment]
I can confirm that with this change the artefacts are gone (I checked a couple of problematic glyphs of various fonts).
However, at huge scale, diagonal lines are slightly wavy now:
![image](https://user-images.githubusercontent.com/33656504/107997546-4b81f700-6fe3-11eb-83b0-170c8dc19588.png)
The lower row is how it was before and you can see that the lines looked absolutely straight.
This is not an issue for me personally because I used the old version and had already corrected the pixel artefacts manually in GIMP. Btw, I packed four fonts of a font family in the colour channels of a texture (regular in red, italic in green, bold in blue and bold-italic in alpha). Since I use three font families (serif, sans-serif and monospace) I have only three textures of 2048 x 2048 that contain all glyphs (almost 2300 or 2800 each). Even with this relatively small glyph size your sdfs look amazing at any scale, perfect for my project. So thanks again!
