### ISSUE TITLE
Javascript implementation of glyph generator ?

### ISSUE THREAD

**Issue by sigurdle** [astiopin/sdf_atlas#11]
Hi,
First of all, thanks for a great way to draw fonts in webgl. I've put it into my webapp, but I would like to generate glyphs on the fly as well. Is there an implementation of the glyph generation in javascript ?
If there's not, I'll try to translate a version of it into javascript? would that be ok ?

Thanks,
Sigurd

**Comment by astiopin** [comment]
There is no js version. You can translate it to javascript of course. It's open source, use it whatever you want.
