### ISSUE TITLE
stencilOpSeparate

### ISSUE THREAD

**Issue by sigurdle** [astiopin/sdf_atlas#12]
Is this project alive? I'm implementing this now in javascript (would be nice to get a sign the project is still alive)

I noticed a minor speed improvement
in sdf_gl.cpp

using stencilOpSeparate

		if (true){
			gl.stencilOpSeparate(gl.BACK, gl.KEEP, gl.INCR_WRAP, gl.INCR_WRAP);
			gl.stencilOpSeparate(gl.FRONT, gl.KEEP, gl.DECR_WRAP, gl.DECR_WRAP);

			gl.drawArrays(gl.TRIANGLES, 0, fcount);

		} else {
	               gl.enable(gl.CULL_FACE);

			// Front face (CCW) increases stencil values
			gl.cullFace( gl.FRONT );
			gl.stencilOp( gl.KEEP, gl.INCR_WRAP, gl.INCR_WRAP);
			gl.drawArrays( gl.TRIANGLES, 0, fcount);

			// Back face (CW) decreases
			gl.cullFace(gl.BACK);
			gl.stencilOp(gl.KEEP, gl.DECR_WRAP, gl.DECR_WRAP);
			gl.drawArrays(gl.TRIANGLES, 0, fcount);

			gl.disable(gl.CULL_FACE);
		}

**Comment by astiopin** [comment]
Sorry, I'm not getting email notifications some reason. The project is not dead, but not actively maintained.
