### ISSUE TITLE
Edge artiffacts on fonts with slightly rounded corners

### ISSUE THREAD

**Issue by oomek** [astiopin/sdf_atlas#2]
Since you're active I'll take the oportunity to mention one thing that troubles me. There are some issues with the first stage of glyph drawing when I use fonts with slightly rounded ~~edges~~ corners.
![image](https://user-images.githubusercontent.com/2974860/75148473-a39b5b80-56f7-11ea-9440-cfa088e33810.png)

I've managed to fix it, but not entirely by using GL_MAX blending instead of depth testing. Te artiffacts just moved to the inside of the glyph edge.

**Comment by oomek** [comment]
Here is the part zoomed in
![image](https://user-images.githubusercontent.com/2974860/75148750-4b188e00-56f8-11ea-9513-92028395c7ae.png)

**Comment by oomek** [comment]
This shouldn't be an issue as the shader isn't going that far inside the glyph when doing aa so maybe you are interested in swapping the `line_vertices` gl commands in sdf_gl.cpp to
```
        glEnable( GL_BLEND );
        glBlendEquation( GL_MAX );
        glDrawArrays( GL_TRIANGLES, 0, lcount );
```

**Comment by astiopin** [comment]
What font is this? Can you provide the TTF? Depth testing in theory should give better results since precision of the z-buffer is much higher than 8 bits of alpha channel with GL_MAX.

**Comment by oomek** [comment]
https://github.com/jpt/barlow/blob/master/fonts/ttf/BarlowCondensed-SemiBold.ttf

**Comment by oomek** [comment]
And here are just the quads to visualise the paths
![image](https://user-images.githubusercontent.com/2974860/75150577-a0569e80-56fc-11ea-9a2c-4eec0fa9f5fe.png)
Updated the image, i keep pasting the wrong ones

**Comment by oomek** [comment]
Your theory is absolutely correct, but This was a tradeoff as the artiffacts were more visible on the small fonts than any potential loss of the precission. Maybe the depth testing could be turned `upside down` so the artiffacts are inside the glyph like when using GL_MAX ? What do you think?

**Comment by astiopin** [comment]
The problem may be with the way I'm dealing with the straight lines. They are treated as an almost-straight parabola segments. Looks like this 'almost' is not enough. Try setting higher precision [here](https://github.com/astiopin/sdf_atlas/blob/master/src/parabola.cpp#L34). Probably 1e-9 is enough.

**Comment by oomek** [comment]
Ive tried 1e-9 and higher, the dent turned to noise but on the other side
![image](https://user-images.githubusercontent.com/2974860/75154012-a3ee2380-5704-11ea-9865-ac6c90d9e224.png)
I'm upping the levels in PS to show it.

**Comment by oomek** [comment]
Increasing the precission even more is making it worse
![image](https://user-images.githubusercontent.com/2974860/75155176-5921db00-5707-11ea-9e31-5e0755490261.png)

**Comment by astiopin** [comment]
Cubic solver in the shader can't cope with such values. The floating precision there is not enough. Lowering precision makes lines straighter, but increases the noise. I've got an iterative algorithm for the cubic solver with a better precision. Trying to integrate it now.

**Comment by astiopin** [comment]
Maybe the better way is to treat lines as actual lines in the shader, with branching on a segment type.

**Comment by oomek** [comment]
Cool, for the lines maybe it's better to use a simple signed distance field from the center of the quad with radius = half the quad size? It's a 1 line formula I use for rounding corners of bitmaps.

Oh and btw, I saw your images explaining how this works. There is a 0.5 brightness on the edge of the glyph which should equal to 127.5, but the produced bitmap has 145-147 on the edge, doesn't it make glyphs fatter at smaller sizes?

And another btw. I see you are using smoothstep and additional contrast in the rendering shader. Should't the antialiased line be linear?

```
float linearstep( float a, float b, float x )
{
    return clamp(( x - a ) / ( b - a ), 0.0, 1.0 );
}
```
That requires lowering the scales and removing contrast in the shader.

**Comment by oomek** [comment]
Here is what I meant regarding the outline colour.
![image](https://user-images.githubusercontent.com/2974860/75159941-12d17980-5711-11ea-9488-4b8cfa82cefa.png)

**Comment by astiopin** [comment]
OK, updated with a new cubic solver.

> Cool, for the lines maybe it's better to use a simple signed distance field from the center of the quad with radius = half the quad size? It's a 1 line formula I use for rounding corners of bitmaps.

I'll probably stick with a parabola segment approach for now since it works surprisingly well with even 1e-16 precision with a new solver. Not sure about mobile though.

> There is a 0.5 brightness on the edge of the glyph which should equal to 127.5, but the produced bitmap has 145-147 on the edge, doesn't it make glyphs fatter at smaller sizes?

127.5 only happens when the contour line goes exactly through the pixel center. This is not always the case, so you can get values that are slightly off 0.5. 

> I see you are using smoothstep and additional contrast in the rendering shader. Should't the antialiased line be linear?

Original Valve paper used smoothstep, so I made it that way. Not entirely sure why, probably some  linear color - SRGB conversion mess.

**Comment by oomek** [comment]
Srgb has an exponential curve accounting for display gamma correction. Smoothstep is linear with mid point mapped to 0.5 and with both ends rounded. I would go with linear, as smoothstep is a bit lazy choice in my opinion. I'm gonna test your new solver, thanks.

**Comment by oomek** [comment]
> 127.5 only happens when the contour line goes exactly through the pixel center. This is not always the case, so you can get values that are slightly off 0.5.

I'm not sure if I follow your thoughts. Should't it be less than 127 when it's off the pixel center?

**Comment by astiopin** [comment]
>Should't it be less than 127 when it's off the pixel center?

Indeed. I've just tested with various fonts and settings, and it's always less than 128. Not sure how you get 148 there.

**Comment by oomek** [comment]
`sdf_atlas -f BarlowCondensed-SemiBold.ttf -o barlow -th 1024 -bs 16`
Btw, your new solver with 1e-9 precission gives outstanding results!

**Comment by astiopin** [comment]
I'm getting 124 on both solvers. Weird.

![barlow](https://user-images.githubusercontent.com/25879628/75164327-b5015980-5731-11ea-8303-fe03e352e67c.png)

**Comment by oomek** [comment]
Damn photoshop! All good mate. it was defaulting to 20% compensation instead of Gamma 2.2

![image](https://user-images.githubusercontent.com/2974860/75166032-313c7280-571b-11ea-8458-e84926493911.png)

**Comment by astiopin** [comment]
I'm testing with GIMP. It's not sophisticated enough for playing tricks like that.

**Comment by oomek** [comment]
Using dumber apps is sometimes for the better. Modern apps try to be too smart.
There is one issue remaining. The webgl demo shows blank page when I do not use `-th 1024` argument. When I do it I get ^2 texture with glyphs aligned to the bottom and it shows in the demo.

**Comment by astiopin** [comment]
>The webgl demo shows blank page when I do not use -th 1024 

I've updated the demo to support NPOT textures.
