### ISSUE TITLE
General Thoughts/Improvements

### ISSUE THREAD

**Issue by DanielHerchenbach** [astiopin/sdf_atlas#8]
First of all I totally admire the work done in /sdf_atlas and /webgl_fonts. It solves a very complex problem with relatively simple means, really ingenious! Because it has been extremely useful to me I want to share some thoughts:
- You scale the font metrics in such a way that ascent + abs(descent) equals the row height (without SDF borders) in texture coordinates. This is a smart way to save some multiplications when using the export for text rendering because the font metrices and the texture coordinates can make use of the same scaling factors. However, I find it a bit counterintuitive to combine texture units and font metrics already in the export. I personally prefer scaling the font metrics so that ascent equals 1. This makes the text layout itself easier for me because I only need to multiply by the font size in pixels to get the font metrics in terms of screen pixels.
- I think a useful option would be to add the option to export ALL found glyphs in a font.
- Currently, all glyph textures have the same height. This may be suboptimal when a glyph does not occupy the full row height. I would like to calculate the exact bounding box height of the glyph and export not only _bearingX_ but also _bearingY_. This format is also more flexible once someone wants to use rectangle packing to fit more glyphs into a texture.
- I am also considering to change the export for faster look up in javascript (may need more benchmarking): make all object keys numeric, i.e. use the code point of the char instead of the char itself. This also means that I am storing the kerning pairs in nested objects with the left and right char code point as separate keys.

I have implemented these ideas locally.

**Comment by weichx** [comment]
@DanielHerchenbach are you willing to share the updates you've made locally? I'm running into a lot of the things you've already mentioned in using this

**Comment by DanielHerchenbach** [comment]
Sure. I am gonna create a pull request both for this repo and webgl_fonts. Within the next days, maybe even tomorrow.

**Comment by weichx** [comment]
Fantastic, thanks a lot!

**Comment by DanielHerchenbach** [comment]
@weichx you are welcome :-)
I eventually did not create pull requests because my fork is a bit cluttered with Visual Studio files but you will find all relevant changes here:
https://github.com/DanielHerchenbach/sdf_atlas/tree/master/src

For the demo (webgl_fonts), I have not made too many changes in the code and they should be already clear from the issues I created. 
Cheers!

**Comment by weichx** [comment]
@DanielHerchenbach (Posting here because I couldn't open an issue in your fork) Thanks for sharing that, looks pretty good to me, I have one question about what you did with the row_height property. In the original version row_height was used as a glyph metric for height and all glyphs had the same height. In your fork it seems row height is still there but I couldn't tell if it is still meant to be used for rendering or if you just kept it as a pseudo atlas-packer metric. I see it used in a few places still to compute scale. Without seeing a rendering example like in the webgl_fonts repo I'm not totally sure how I'd use this now, could you elaborate a little bit? 

Thanks

**Comment by DanielHerchenbach** [comment]
@weichx The row height (exported as "glyphHeight") is used only for two things:
1.) As a raster while generating the texture atlas in order to ensure that the glyphs do not overlap. Most glyphs do not occupy the complete row height but I have not implemented an algorithm that packs the glyph bounding boxes more densly. This is possible however without changing the format of the json export.
2.) To know how many pixels in the glyph atlas correspond to the ascent of the font (all font metrics are normalized to ascent = 1). The row height equals the maximum possible height of a glyph which is ascent + abs(descent) = 1 - descent. So the conversion factor is:
**factorTexturePxToMetrics = (1 - font.metrics.descent) / font.metrics.glyphHeight;**
One could export this factor directly and not use the row height at all on the javascript side. However, that doesn't feel natural to me because you still need to export the falloff (border size) in terms of texture pixels.

You should be able to create issues now.
I am preparing a fork of webgl_fonts to show how to use this export. This fork will address all other issues created by my (such as more bayer patterns and fixing of kerning) and also include proper blending proposed by @oomek.

@astiopin If you need a pull request, please let me know.

**Comment by weichx** [comment]
Awesome, I'll play around with this and see how it goes. Thanks @astiopin for the great library and @DanielHerchenbach for the tweaks & improvements

**Comment by DanielHerchenbach** [comment]
@weichx here you go:
https://github.com/DanielHerchenbach/webgl_fonts/
or live demo:
https://www.free-insight.org/webgl_fonts/

In case I did not make myself clear: With the new export and demo the fragment shader is executed only for pixels inside of the actual bounding box of each glyph, not the entire row height.
Note that this demo makes the ascent (not the cap height) as high as the chosen font size. This seems to match more the way the browser interpretes font pixel sizes.

**Comment by weichx** [comment]
@DanielHerchenbach Thanks a lot for your work on this, and for sharing it. I've been struggling for a while to get SDF fonts to look good at small sizes and this is certainly the best implementation of that that I've seen so far. I'm also trying to do atlas generation on the fly so I don't have to pre-bake texture atlases and I'm pretty sure I can make that work now with your latest update.

**Comment by DanielHerchenbach** [comment]
@weichx You are welcome. True, I haven't found anything comparable either.
I have now also added proper blending (astiopin/webgl_fonts#7).
I probably made a stupid mistake yesterday, now it works (even for me using premultiplied alpha). The difference is noticable for the string "ff" in the Arimo font for example or any glyphs that overlap with each other.

**Comment by astiopin** [comment]
> First of all I totally admire the work done in /sdf_atlas and /webgl_fonts

Thanks. The atlas generator was never meant to be used as a production tool - just a small demo of the fast SDF calculation.

> You scale the font metrics in such a way

That's mostly for historical reason - that's how it was made in the demo originally, so I outputting it to the atlas that way.

> I think a useful option would be to add the option to export ALL found glyphs in a font

Actually the right way is to export subglyphs, so ё, ö could be constructed from e, o and umlaut subglyphs.

> Currently, all glyph textures have the same height. 

Yeah, I should change that. That was the laziest way to do it.

> This format is also more flexible once someone wants to use rectangle packing to fit more glyphs into a texture.

Rectangle packing is quite complex, sorting glyphs by height is much easier to do and gives comparable results.

**Comment by astiopin** [comment]
@weichx 
> I'm also trying to do atlas generation on the fly

Beware, that most mobile GPUs don't support changing fragment depth in the shader. So the generator won't work on mobile without serious fixes.

https://opengles.gpuinfo.org/listreports.php?extension=GL_EXT_frag_depth

**Comment by weichx** [comment]
Thanks for pointing that, I hadn't read the shader the closely and missed that it was setting the fragment depth. I was considering doing this with compute shaders instead of a vertex / fragment setup since my target platform(s) support them, which I believe would be able to do an equivalent operation.

**Comment by weichx** [comment]
@astiopin Regarding subglyphs, I am already using Harfbuzz for shaping my programs so just exporting subglyphs would be a huge win for my use case. Would extracting subglyphs here be an easy thing to add? A quick google search didn't reveal much on the topic

**Comment by astiopin** [comment]
@weichx 

>Would extracting subglyphs here be an easy thing to add?

Subglyph loading is there. Every composite [glyph](https://github.com/astiopin/sdf_atlas/blob/3cd8b39cb5e6ec75b5a81fe5e3f8ae45bc58e9e3/src/font.h#L31) in a font contains a list of [subglyphs](https://github.com/astiopin/sdf_atlas/blob/3cd8b39cb5e6ec75b5a81fe5e3f8ae45bc58e9e3/src/font.h#L62) with transforms. So the only things missing are layout algorithm and new json file format.

**Comment by weichx** [comment]
Good to know, ill see if I can find a way to address them in an export and inform the shaping engine that it should try to combine subglyphs instead of looking for full ones
